apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: local-claim
  namespace: dev
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 5Gi
  storageClassName: my-local-path
