apiVersion: v1
kind: Pod
metadata:
  labels:
    run: time-check
  name: time-check
  namespace: dvl1987
spec:
  containers:
  - image: busybox
    name: time-check
    envFrom:
    - configMapRef:
        name: time-config
    command: ["/bin/sh"]
    args: ["-c", "while true; do date; sleep $TIME_FREQ;done > /opt/time/time-check.log"]
    volumeMounts:
    - mountPath: /opt/time
      name: log-volume
  volumes:
  - name: log-volume
    emptyDir: {}
